# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 522915ce6c791134130007a93048319a75ada5f90fddb4b88fbfbd91cb9c2bb24a3d76e7f033d878668272b56976f5b5528219f4581e5330e71af66b985e723b

test:
  secret_key_base: 1871601fff62034a63d15d28afda7fc97b7a6101f32f4e5ce69a388377e12d4372a0f6d40cc6566df937330f6d171948af251539067a743b2df30a8247aa5e84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
